version: 0.2

env:
  variables:
    FOO: BAR

phases:
  install:
    commands:
      - dnf -qy upgrade
  pre_build:
    commands:
      - dnf -qy install /usr/bin/aws
    finally:
      - dnf clean all
  build:
    commands:
      - "aws sts get-caller-identity"
      - "aws --region us-east-2 ec2 describe-instances"
  post_build:
    commands:
      - cat /etc/fedora-release
